config-version = 2
start-at-login = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

automatically-unhide-macos-hidden-apps = true

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 2
5 = 2
6 = 2

[mode.main.binding]
cmd-h = 'focus left'
cmd-j = 'focus down'
cmd-k = 'focus up'
cmd-l = 'focus right'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'

cmd-alt-minus = 'resize smart -200'
cmd-alt-equal = 'resize smart +200'

cmd-alt-1 = 'move-node-to-workspace --focus-follows-window 1'
cmd-alt-2 = 'move-node-to-workspace --focus-follows-window 2'
cmd-alt-3 = 'move-node-to-workspace --focus-follows-window 3'
cmd-alt-4 = 'move-node-to-workspace --focus-follows-window 4'
cmd-alt-5 = 'move-node-to-workspace --focus-follows-window 5'
cmd-alt-6 = 'move-node-to-workspace --focus-follows-window 6'

cmd-slash = 'layout tiles horizontal vertical'
cmd-backslash = 'layout accordion horizontal vertical'
cmd-shift-enter = 'move-node-to-monitor --wrap-around --focus-follows-window next'

