[settings]
idiomatic_version_file_enable_tools = ["ruby", "go", "node", "java", "python"]

[tools]
"aqua:Kitware/CMake" = "4.2.1"
deno = "2.6.0"
"github:tailwindlabs/tailwindcss" = "4.1.18"
"github:nolanderc/glsl_analyzer" = "1.7.1"
go = "1.25.5"
golangci-lint = "2.7.2"
golangci-lint-langserver = "0.0.11"
gradle = "9.2.1"
java = "21"
lua = "5.1"
make = "4.4.1"
maven = "3.9.11"
meson = "1.10.0"
ninja = "1.13.2"
node = "25.2.1"
python = "3.14.2"
ruby = "3.4.7"
rust = "1.92.0"
rust-analyzer = "2025-12-08"
shellspec = "0.28.1"
usage = "2.9.0"
