[settings]
idiomatic_version_file_enable_tools = ["ruby", "go", "node", "java", "python"]

[settings.ruby]
compile = false

[tools]
"github:tailwindlabs/tailwindcss" = "4.1.18"
"github:nolanderc/glsl_analyzer" = "1.7.1"
go = "1.25.5"
golangci-lint = "2.7.2"
golangci-lint-langserver = "0.0.11"
lua = "5.1"
maven = "3.9.11"
ninja = "1.13.2"
node = "25.2.1"
python = "3.14.2"
ruby = "3.4.7"
